/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package serial_read;

import arduino.Arduino;

import com.fazecast.jSerialComm.*;

public class SerialRead {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        
        Arduino a = new Arduino("/dev/ttyUSB0", 9600);      
        a.openConnection();
        
        while(true){
           System.out.println("******* reading *******");
           String s = a.serialReadAll(); //read from serial until getting a linebreak (\n)
           System.out.println(s);
           try {
		Thread.sleep(100);
		} catch (InterruptedException e2) {
		   e2.printStackTrace();
	        }
        }
        
        
    }
}
