/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package write;

import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;

import arduino.NRJ;

public class App {

	public static void main(String[] args) {
		try {
   		   NRJ a = new NRJ("/dev/ttyUSB0", 9600);  //serial port: possibly must be changed in different systems.    
		   a.openConnection();

		   BufferedReader br = new BufferedReader(new InputStreamReader(System.in));
		   System.out.print("Type the string to send to the serial: ");
		
			String s = br.readLine();
			System.out.println("sending " + s + "...");
			a.serialWrite(s);
		} catch (Exception e) {
			e.printStackTrace();
		}

	}
}
